---
- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    uri_method: POST


  vars_files:
    - ../.private/autows-creds.yaml

  tasks:


  - name: CREATE AS3 DEPLOY
    uri:
      url: https://35.177.202.229/mgmt/shared/appsvcs/declare
      user: "{{ big_usr }}"
      password: "{{ big_pwd }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','as3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
